// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(TemperaturaContext))]
    partial class TemperaturaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoApi.Models.Temperatura", b =>
                {
                    b.Property<int>("IdTemperatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTemperatura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTemperatura"));

                    b.Property<int>("IdBiodigestor")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaTemperatura")
                        .HasColumnType("datetime2");

                    b.Property<float>("nivelTemperatura")
                        .HasColumnType("real");

                    b.HasKey("IdTemperatura");

                    b.HasIndex("IdTemperatura")
                        .IsUnique();

                    b.ToTable("Temperatura", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
